# Generated by Django 6.0.5 on 2026-05-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(default=None, upload_to='', verbose_name='Путь к картинке'),
        ),
    ]
